### PR TITLE
Fix offcanvas toggle when clicking Technology menu item in desktop mode

### LINKED ISSUE #128: Clicking the Technology menu item causes part of the offcanvas overlay to appear
Clicking the Technology menu item causes the opacity layer of the offcanvas to appear over the screen.  This disables scrolling as well.

The overlay goes away when clicking.

### PR DESCRIPTION
**Pull request by alexandercyu**
Added condition so the offcanvas doesn't toggle in desktop screens.  Fixes #128

### CODE REVIEW

File: templates/site/js/menu.js [hunk 1]
```diff
@@ -21,7 +21,9 @@ document.addEventListener("DOMContentLoaded", function () {
     })
 
     technologyButton.addEventListener("click", () => {
-        bsOffcanvas.toggle();
+        if(window.window.innerWidth < 990){
```
Comment (mishaschwartz) [inline templates/site/js/menu.js:24]: why not just:

```js
bsOffcanvas.hide();
```

So we don't have to keep track of screen widths?

Comment (alexandercyu) [reply templates/site/js/menu.js]: That's definitely a more encompassing solution.  Changed to uses hide.

**Review by mishaschwartz — APPROVED** [review]
